 FORMAT: 1A
 HOST: http://localhost:3000

# VUTTR (Very Useful Tools to Remember) 
The application is a simple repository for managing tools with their names, links, descriptions and tags.

# Tools API

## Tools [/tools]

This feature makes it possible to create a new record of a tool in the database and view it with a filter

### Create New Tool [POST]

+ Request Create New Tool (application/json)

    {
        "title": "hotel",
        "link": "https://github.com/typicode/hotel",
        "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
        "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
    }

+ Response 201 Created

      {
        "title": "hotel",
        "link": "https://github.com/typicode/hotel",
        "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
        "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
        "_id": 1 // AutoGenerate
    }


### GET Filter Tools By Tag[/tools{?tag=}]

Resource that searches for tools filtered by tag.

We have added the query URI parameter `tag`. This parameter is
used to filter the tools from the Strings contained in the Tags field.


+ Response 200 (application/json)
    + Attributes (array[tool])

+ Response 404 (application/json)
    + Attributes (Error)
    

### Retrieve all Tools [GET]

+ Parameters

    + page (number, required) - Define the page to bring the results.
        + Default: `1`
    + limit (number, required) - The maximum number of results to return per page.
        + Default: `10`

+ Response 200 (application/json)




## Error (object)
+ code: 400 (number) - Status code
+ message (string) - Status message
+ description (string) - Status description